server:
  port: 9998
spring:
  application:
    name: yadmin-amq
  boot:
    admin:
      client:
        url: http://127.0.0.1:9996

#debug: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
