spring:
  # 环境 dev|test|prod quart定时任务
  profiles:
    active: dev,quartz
  main:
    #允许Bean重复注入，后者覆盖前者
    allow-bean-definition-overriding: true
  resources:
    #这个要配置下，不然本地上传访问不到文件
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/upload

ytrue:
  oss:
    engine: local
    local:
      file-host: upload/file
      domain: http://127.0.0.1:9995
  security:
    client-id: admin
    client-secret:
    jwt:
      signing-key: 432432hdfgdhg@676@&*&*(&*)(*)$3543ktjn45j6h546%$^%$hgfhmf
  #文档
  document:
    enabled: true
    basic:
      enable: true
      username: yang
      password: yang
#    title: yadmin后台文档
#    description: yadmin后台在线文档
#    version: 1.0
    production: false
    docket:
      system:
        title: 系统模块
        base-package: com.ytrue.yadmin.modules.system
      mall:
        title: 商城模块
        base-package: com.ytrue.yadmin.modules.mall




  unified:
    dispose:
      exception:
        enabled: true
      response-data:
        enabled: true
        advice-filter-url: [/v2/api-docs,/swagger-resources,/actuator/**]
