#针对ytrue配置
ytrue:
  # swagger配置
  document:
    # 开启文档
    enabled: true
    # 是否是线上模式
    production: false
    # 认证配置
    basic:
      # 开启认证
      enable: true
      # 用户名
      username: yadmin
      # 密码
      password: 111111
    # 全局参数配置
    global-operation-parameters:
      # 认证头
      - name: Authorization
        description: 认证头
        modelRef: String
        parameter-type: header
        required: true
        default-value: 123456
        allow-empty-value: false
    # 分组文档
    docket:
      # 用户模块
      user:
        title: 用户管理
        base-package: com.ytrue.yadmin.modules.system.controller.user
        path-regex: /user.*
      # 测试模块
      test:
        title: 测试管理
        base-package: com.ytrue.yadmin.modules.system.controller.test
        path-regex: /test.*
